2022-04-17 16:43:17,811:domconnect.views:Site Source Service обновлены.
2022-04-17 16:51:57,067:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 16:52:11,882:domconnect.views:Ошибка upgradeSiteSource: try: DcCatalogSourceSEO matching query does not exist.
2022-04-17 16:54:13,051:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 16:54:21,413:domconnect.views:Ошибка upgradeSiteSource: try: DcCatalogSourceSEO matching query does not exist.
2022-04-17 16:56:21,949:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 16:56:31,175:domconnect.views:Site Source Service обновлены.
2022-04-17 17:03:54,127:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 17:04:18,503:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 17:04:34,362:domconnect.views:Site Source Service обновлены.
2022-04-17 17:04:55,323:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 17:05:02,279:domconnect.views:Site Source Service обновлены.
2022-04-17 17:05:35,260:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 17:05:46,939:domconnect.views:Site Source Service обновлены.
2022-04-17 17:15:51,296:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 17:16:33,349:domconnect.views:Ошибка Икточник: BEELINE-ru-S-74993806540 отсутствует в каталоге.
2022-04-17 17:16:33,576:domconnect.views:Ошибка Икточник: TTK-sev-G-88007753740 отсутствует в каталоге.
2022-04-17 17:16:33,775:domconnect.views:Site Source Service обновлены.
2022-04-17 17:18:17,623:domconnect.lib_seo:Обновение данных SEO запущено.
2022-04-17 17:18:18,844:domconnect.lib_seo:Загрузка завершена. Обработано сделок: 0. Ошибок: 0
2022-04-17 17:18:25,474:domconnect.lib_seo:Загрузка завершена. Обработано лидов: 181. Ошибок: 0
2022-04-17 17:24:42,066:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\lib_seo.py changed, reloading.
2022-04-17 17:29:23,879:domconnect.lib_seo:Обновение данных SEO запущено.
2022-04-17 17:29:25,058:domconnect.lib_seo:Загрузка завершена. Обработано сделок: 0. Ошибок: 0
2022-04-17 17:29:27,373:domconnect.lib_seo:Загрузка завершена. Обработано лидов: 51. Ошибок: 0
2022-04-17 17:35:32,673:domconnect.lib_seo:Расчет и сохранение данных SEO в кэш закончено.
2022-04-17 20:24:10,018:django.request:Internal Server Error: /domconnect/sites
Traceback (most recent call last):
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\Dev\dj_domconnect\domconnect\views.py", line 114, in sites
    new_form.provider = request.POST.get("provider")
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 214, in __set__
    raise ValueError(
ValueError: Cannot assign "'14'": "DcSiteSEO.provider" must be a "DcCatalogProviderSEO" instance.
2022-04-17 20:26:19,902:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 20:30:00,124:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 20:30:26,461:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 22:03:21,869:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 22:05:57,974:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 22:07:50,283:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-17 22:08:21,120:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 09:47:30,391:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 09:47:48,488:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 09:47:54,588:django.request:Internal Server Error: /domconnect/sites
Traceback (most recent call last):
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\Dev\dj_domconnect\domconnect\views.py", line 140, in sites
    return render(request, 'domconnect/sites.html', context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'site_edit row.id' not found. 'site_edit row.id' is not a valid view function or pattern name.
2022-04-18 09:47:54,939:django.request:Not Found: /favicon.ico
2022-04-18 09:56:42,768:django.request:Internal Server Error: /domconnect/sites
Traceback (most recent call last):
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\Dev\dj_domconnect\domconnect\views.py", line 140, in sites
    return render(request, 'domconnect/sites.html', context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 477, in parse
    raise self.error(token, e)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 477, in parse
    raise self.error(token, e)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 477, in parse
    raise self.error(token, e)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\defaulttags.py", line 1359, in url
    viewname = parser.compile_filter(bits[1])
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 562, in compile_filter
    return FilterExpression(token, self)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 661, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '`domconnect:site_edit`' from '`domconnect:site_edit`'
2022-04-18 10:09:29,401:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 10:40:26,980:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 10:53:23,379:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 10:54:14,530:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 10:54:51,945:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:06:57,963:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:07:05,821:django.request:Internal Server Error: /domconnect/site_edit/0
Traceback (most recent call last):
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\Dev\dj_domconnect\domconnect\views.py", line 151, in site_edit
    print(request.get('num'))
AttributeError: 'WSGIRequest' object has no attribute 'get'
2022-04-18 11:07:50,747:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:10:14,497:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:17:20,045:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:24:32,031:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:27:14,589:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:27:24,155:django.request:Internal Server Error: /domconnect/site_edit/0
Traceback (most recent call last):
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\Dev\dj_domconnect\domconnect\views.py", line 161, in site_edit
    obj_site = objs_site[0]
TypeError: 'DcSiteSEO' object is not subscriptable
2022-04-18 11:28:05,601:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:28:16,954:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:29:59,657:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:30:11,856:django.request:Internal Server Error: /domconnect/site_edit/0
Traceback (most recent call last):
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\Dev\dj_domconnect\domconnect\views.py", line 167, in site_edit
    return redirect('home')
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\shortcuts.py", line 41, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\shortcuts.py", line 131, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
2022-04-18 11:30:41,430:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:30:46,190:django.request:Not Found: /domconnect/site_edit/domconnect/home
2022-04-18 11:31:04,393:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:31:29,859:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:36:17,015:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:37:18,801:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:38:01,737:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:42:44,224:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:46:40,382:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:56:47,387:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 11:57:03,096:domconnect.views:Site Source Service обновлены.
2022-04-18 11:59:57,224:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 12:03:36,307:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 12:11:59,380:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 12:17:28,187:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 12:18:27,304:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 13:55:48,295:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:00:14,681:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:01:33,304:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:05:16,213:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:06:41,970:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:09:46,728:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:13:14,782:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:18:56,650:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:23:36,348:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:24:26,726:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:27:10,633:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:27:41,838:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 14:56:51,496:django.security.csrf:Forbidden (CSRF token missing or incorrect.): /domconnect/sites
2022-04-18 15:14:37,976:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 15:21:59,722:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 15:23:30,004:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 15:30:58,352:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 15:36:14,725:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 15:44:17,865:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 15:45:04,357:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 15:45:35,591:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 15:45:40,549:django.request:Internal Server Error: /domconnect/sites
Traceback (most recent call last):
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\Dev\dj_domconnect\domconnect\views.py", line 129, in sites
    objs_site[k-1], objs_site[k] = objs_site[k], objs_site[k-1]
TypeError: 'QuerySet' object does not support item assignment
2022-04-18 15:47:10,664:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 15:47:18,205:django.request:Internal Server Error: /domconnect/sites
Traceback (most recent call last):
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\Dev\dj_domconnect\domconnect\views.py", line 133, in sites
    objs_site[k-1], objs_site[k] = objs_site[k], objs_site[k-1]
TypeError: 'QuerySet' object does not support item assignment
2022-04-18 15:48:02,070:django.request:Internal Server Error: /domconnect/sites
Traceback (most recent call last):
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\Dev\dj_domconnect\domconnect\views.py", line 133, in sites
    objs_site[k-1], objs_site[k] = objs_site[k], objs_site[k-1]
TypeError: 'QuerySet' object does not support item assignment
2022-04-18 15:57:08,152:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 15:58:17,389:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:00:17,376:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:00:42,877:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:07:05,741:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:07:52,119:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:08:31,405:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:10:48,911:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:11:39,091:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:12:19,776:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:13:51,091:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:16:53,220:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:20:43,318:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:21:59,144:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:22:21,417:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:23:05,329:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:24:37,558:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:34:40,785:domconnect.views:Site Source Service обновлены.
2022-04-18 16:40:00,538:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
2022-04-18 16:40:06,609:django.request:Not Found: /domconnect/sources
2022-04-18 16:40:12,110:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "c:\Dev\dj_domconnect\app\views.py", line 27, in index
    return render(request, 'app/index.html', context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "c:\Dev\dj_domconnect\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'sources' not found. 'sources' is not a valid view function or pattern name.
2022-04-18 16:40:29,626:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\urls.py changed, reloading.
2022-04-18 16:40:47,806:django.utils.autoreload:C:\Dev\dj_domconnect\domconnect\views.py changed, reloading.
